export const flocksMock = [
  {
    name: "Matuê",
    code: "BR-044",
    breed: "Nelore",
    phase: "Garrota",
    age: "1a",
    weight: "142kg",
    alerts: 1,
    goal: "Novilha",
    currentWeight: 142,
    goalWeight: 180,
    lastWeighing: "09/12/2026",
    events: 2,
    colorCard: "#622BD0",
  },
  {
    name: "Luna",
    code: "BR-021",
    breed: "Nelore",
    phase: "Novilha",
    age: "2a",
    weight: "180kg",
    alerts: 0,
    goal: "Primípara",
    currentWeight: 180,
    goalWeight: 200,
    lastWeighing: "02/12/2026",
    events: 3,
    colorCard: "#28C2B0",
  },
  {
    name: "Brisa",
    code: "BR-078",
    breed: "Angus",
    phase: "Bezerra",
    age: "6m",
    weight: "90kg",
    alerts: 2,
    goal: "Garrota",
    currentWeight: 90,
    goalWeight: 140,
    lastWeighing: "10/12/2026",
    events: 1,
    colorCard: "#B32A9A",
  },
  {
    name: "Estrela",
    code: "BR-011",
    breed: "Nelore",
    phase: "Multiparta",
    age: "5a",
    weight: "210kg",
    alerts: 0,
    goal: "Manutenção",
    currentWeight: 210,
    goalWeight: 210,
    lastWeighing: "01/12/2026",
    events: 5,
    colorCard: "#FF7700",
  },
  {
    name: "Safira",
    code: "BR-056",
    breed: "Gir",
    phase: "Primípara",
    age: "3a",
    weight: "190kg",
    alerts: 1,
    goal: "Multiparta",
    currentWeight: 190,
    goalWeight: 210,
    lastWeighing: "05/12/2026",
    events: 2,
    colorCard: "#0004FF",
  },
  {
    name: "Nina",
    code: "BR-099",
    breed: "Holandês",
    phase: "Inativa",
    age: "6a",
    weight: "230kg",
    alerts: 3,
    goal: "Reavaliação",
    currentWeight: 230,
    goalWeight: 220,
    lastWeighing: "20/11/2026",
    events: 4,
    colorCard: "#71717A",
  },
];
